<?php
/**
 * Single Tutorial Template.
 *
 * @package QWE_Developer_Flavor
 */

get_header();

if ( have_posts() ) : the_post();
?>

<?php qwe_breadcrumbs(); ?>

<article class="single-tutorial" itemscope itemtype="https://schema.org/Article">

    <!-- Tutorial Header -->
    <header class="tutorial-header">
        <div class="container">
            <?php qwe_tutorial_categories(); ?>
            <h1 class="tutorial-header__title" itemprop="headline"><?php the_title(); ?></h1>

            <?php if ( has_excerpt() ) : ?>
                <p class="tutorial-header__excerpt" itemprop="description"><?php echo esc_html( get_the_excerpt() ); ?></p>
            <?php endif; ?>

            <?php qwe_tutorial_meta(); ?>
        </div>
    </header>

    <!-- Tutorial Content with TOC Sidebar -->
    <div class="tutorial-layout">
        <div class="container">
            <div class="tutorial-layout__grid">

                <!-- Table of Contents (generated by JS) -->
                <aside class="tutorial-toc" id="tutorial-toc" aria-label="<?php esc_attr_e( 'Table of Contents', 'qwe-developer-flavor' ); ?>">
                    <div class="tutorial-toc__inner">
                        <h3 class="tutorial-toc__title"><?php esc_html_e( 'Contents', 'qwe-developer-flavor' ); ?></h3>
                        <nav class="tutorial-toc__nav" id="toc-nav">
                            <!-- Populated by JavaScript -->
                        </nav>
                    </div>
                </aside>

                <!-- Main Content -->
                <div class="tutorial-content" itemprop="articleBody">
                    <?php
                    if ( has_post_thumbnail() ) :
                    ?>
                        <figure class="tutorial-content__hero-image">
                            <?php the_post_thumbnail( 'qwe-tutorial-hero', array( 'itemprop' => 'image' ) ); ?>
                        </figure>
                    <?php endif; ?>

                    <?php the_content(); ?>
                </div>

            </div>
        </div>
    </div>

    <!-- Post Navigation -->
    <?php qwe_post_navigation(); ?>

</article>

<!-- Related Tutorials -->
<?php qwe_related_tutorials( 3 ); ?>

<?php
endif;

get_footer();
