<?php
/**
 * Database Setup & Keyword Seeder
 *
 * Run once: php auto-publish/setup.php
 * Or re-run to add new keywords (existing ones are skipped via INSERT OR IGNORE).
 *
 * @package QWE_Auto_Publish
 */

require_once __DIR__ . '/db.php';

// Initialize tables.
QWE_DB::init_tables();
echo "Database tables created.\n";

// ============================================================
// Long-tail keyword seed data
// Format: 'category_slug' => array( array( 'keyword', 'difficulty' ), ... )
// ============================================================

$keywords = array(

    // ------- ChatGPT & LLMs -------
    'chatgpt-llms' => array(
        array( 'how to use ChatGPT for beginners complete guide', 'beginner' ),
        array( 'best ChatGPT prompts for students', 'beginner' ),
        array( 'ChatGPT vs Claude which AI chatbot is better', 'beginner' ),
        array( 'how to write better prompts for ChatGPT', 'beginner' ),
        array( 'ChatGPT prompt engineering tips and tricks', 'intermediate' ),
        array( 'how to use ChatGPT to learn a new language', 'beginner' ),
        array( 'ChatGPT custom instructions how to set up', 'beginner' ),
        array( 'how to use ChatGPT for research papers', 'intermediate' ),
        array( 'ChatGPT plugins best ones to install', 'intermediate' ),
        array( 'how to use ChatGPT memory feature', 'beginner' ),
        array( 'ChatGPT for teachers classroom ideas', 'beginner' ),
        array( 'how to build a chatbot with ChatGPT API', 'advanced' ),
        array( 'ChatGPT system prompts explained for beginners', 'beginner' ),
        array( 'how to use Claude AI for long documents', 'beginner' ),
        array( 'Claude vs ChatGPT for coding tasks comparison', 'intermediate' ),
        array( 'how to use Google Gemini AI complete tutorial', 'beginner' ),
        array( 'best free AI chatbots compared', 'beginner' ),
        array( 'how to use ChatGPT to summarize books', 'beginner' ),
        array( 'ChatGPT for job interview preparation', 'beginner' ),
        array( 'how to use ChatGPT to write emails professionally', 'beginner' ),
        array( 'ChatGPT advanced data analysis feature tutorial', 'intermediate' ),
        array( 'how to use Perplexity AI for research', 'beginner' ),
        array( 'ChatGPT jailbreak prompts do they still work', 'intermediate' ),
        array( 'how to use ChatGPT to create study notes', 'beginner' ),
        array( 'ChatGPT for content creators workflow tips', 'intermediate' ),
        array( 'how to use ChatGPT voice mode', 'beginner' ),
        array( 'best AI chatbot for creative writing', 'beginner' ),
        array( 'how to train ChatGPT on your own data', 'advanced' ),
        array( 'ChatGPT for meal planning and recipes', 'beginner' ),
        array( 'how to use ChatGPT to debug code', 'intermediate' ),
        array( 'ChatGPT temperature and top p settings explained', 'advanced' ),
        array( 'how to use Llama 3 locally on your computer', 'advanced' ),
        array( 'best open source LLM alternatives to ChatGPT', 'intermediate' ),
        array( 'how to use ChatGPT to plan a trip', 'beginner' ),
        array( 'ChatGPT for brainstorming business ideas', 'beginner' ),
        array( 'how to use ChatGPT API in Python step by step', 'advanced' ),
        array( 'ChatGPT token limits explained and how to work around them', 'intermediate' ),
        array( 'how to use ChatGPT to create presentations', 'beginner' ),
        array( 'ChatGPT for Excel formulas and spreadsheets', 'beginner' ),
        array( 'how to fact check ChatGPT responses', 'beginner' ),
        array( 'ChatGPT for parents helping kids with homework', 'beginner' ),
        array( 'how to use multiple AI chatbots together workflow', 'intermediate' ),
        array( 'ChatGPT canvas feature how to use it', 'beginner' ),
        array( 'how to use ChatGPT to analyze PDF documents', 'beginner' ),
        array( 'ChatGPT for freelancers productivity tips', 'intermediate' ),
        array( 'how to create a GPT custom assistant', 'intermediate' ),
        array( 'best ChatGPT alternatives free and paid', 'beginner' ),
        array( 'how to use ChatGPT with Google Sheets', 'intermediate' ),
        array( 'ChatGPT for social media content creation', 'beginner' ),
        array( 'how to use ChatGPT to write cover letters', 'beginner' ),
    ),

    // ------- AI Art & Design -------
    'ai-art-design' => array(
        array( 'how to use Midjourney for beginners step by step', 'beginner' ),
        array( 'best Midjourney prompts for realistic photos', 'beginner' ),
        array( 'Midjourney vs DALL-E 3 which is better for art', 'beginner' ),
        array( 'how to create a logo with Midjourney', 'beginner' ),
        array( 'Stable Diffusion installation guide Windows', 'intermediate' ),
        array( 'Stable Diffusion best models for realistic images', 'intermediate' ),
        array( 'how to use negative prompts in Stable Diffusion', 'intermediate' ),
        array( 'DALL-E 3 complete tutorial for beginners', 'beginner' ),
        array( 'how to create consistent characters in Midjourney', 'intermediate' ),
        array( 'best AI art generators free to use', 'beginner' ),
        array( 'how to use ControlNet in Stable Diffusion', 'advanced' ),
        array( 'Midjourney style reference feature how to use', 'intermediate' ),
        array( 'how to upscale AI generated images', 'beginner' ),
        array( 'AI art prompt formula for any style', 'beginner' ),
        array( 'how to create AI art for print on demand', 'intermediate' ),
        array( 'Stable Diffusion LoRA training guide for beginners', 'advanced' ),
        array( 'how to remove background from images with AI', 'beginner' ),
        array( 'best AI tools for graphic design', 'beginner' ),
        array( 'how to create AI generated patterns for design', 'intermediate' ),
        array( 'Midjourney aspect ratio settings explained', 'beginner' ),
        array( 'how to use Leonardo AI for image generation', 'beginner' ),
        array( 'AI image generation copyright rules explained', 'beginner' ),
        array( 'how to create book covers with AI art', 'intermediate' ),
        array( 'Stable Diffusion ComfyUI complete tutorial', 'advanced' ),
        array( 'how to use Ideogram AI for text in images', 'beginner' ),
        array( 'best AI tools for UI UX design mockups', 'intermediate' ),
        array( 'how to create AI art in specific artist styles', 'intermediate' ),
        array( 'Midjourney describe feature reverse prompt guide', 'beginner' ),
        array( 'how to use Flux AI image model', 'intermediate' ),
        array( 'AI coloring and recoloring tools for photos', 'beginner' ),
        array( 'how to create seamless textures with AI', 'intermediate' ),
        array( 'best free Stable Diffusion alternatives online', 'beginner' ),
        array( 'how to create AI avatars and profile pictures', 'beginner' ),
        array( 'Midjourney blend feature tutorial', 'beginner' ),
        array( 'how to fix hands and faces in AI generated images', 'intermediate' ),
        array( 'AI fashion design tools and workflows', 'intermediate' ),
        array( 'how to create isometric illustrations with AI', 'intermediate' ),
        array( 'best AI tools for photo editing and enhancement', 'beginner' ),
        array( 'how to use inpainting in Stable Diffusion', 'intermediate' ),
        array( 'AI interior design room visualization tools', 'beginner' ),
        array( 'how to create sticker designs with AI', 'beginner' ),
        array( 'Midjourney chaos and weird parameters explained', 'intermediate' ),
        array( 'how to batch generate images with Stable Diffusion', 'advanced' ),
        array( 'AI product photography tools and techniques', 'intermediate' ),
        array( 'how to create anime art with AI generators', 'beginner' ),
        array( 'best AI image enlarger and enhancer tools', 'beginner' ),
        array( 'how to use AI for architectural visualization', 'intermediate' ),
        array( 'Stable Diffusion prompt weights and syntax guide', 'intermediate' ),
        array( 'how to create social media graphics with AI', 'beginner' ),
        array( 'AI color palette generators for designers', 'beginner' ),
    ),

    // ------- AI Coding -------
    'ai-coding' => array(
        array( 'how to use GitHub Copilot complete guide', 'beginner' ),
        array( 'GitHub Copilot vs Cursor which AI code editor is better', 'beginner' ),
        array( 'how to use ChatGPT for coding beginners', 'beginner' ),
        array( 'best AI coding assistants compared', 'beginner' ),
        array( 'how to use Cursor AI editor for beginners', 'beginner' ),
        array( 'how to build a website with AI tools only', 'beginner' ),
        array( 'ChatGPT for Python programming tutorial', 'beginner' ),
        array( 'how to use AI to learn programming faster', 'beginner' ),
        array( 'best AI tools for web development', 'intermediate' ),
        array( 'how to use Copilot to write unit tests', 'intermediate' ),
        array( 'AI code review tools and best practices', 'intermediate' ),
        array( 'how to use Claude for coding complex projects', 'intermediate' ),
        array( 'best AI tools for debugging code', 'beginner' ),
        array( 'how to build a REST API with AI assistance', 'intermediate' ),
        array( 'AI tools for SQL query writing and optimization', 'beginner' ),
        array( 'how to use AI to refactor legacy code', 'advanced' ),
        array( 'best AI tools for frontend development React', 'intermediate' ),
        array( 'how to create a mobile app with AI no code', 'beginner' ),
        array( 'AI pair programming tips and workflows', 'intermediate' ),
        array( 'how to use Tabnine AI code completion', 'beginner' ),
        array( 'best AI tools for DevOps and automation', 'advanced' ),
        array( 'how to use AI to write documentation', 'beginner' ),
        array( 'ChatGPT for JavaScript and TypeScript development', 'intermediate' ),
        array( 'how to build browser extensions with AI help', 'intermediate' ),
        array( 'AI tools for database design and optimization', 'intermediate' ),
        array( 'how to use Replit AI for collaborative coding', 'beginner' ),
        array( 'best AI tools for CSS and styling', 'beginner' ),
        array( 'how to create WordPress plugins with AI', 'intermediate' ),
        array( 'AI code generation vs hand coding pros and cons', 'beginner' ),
        array( 'how to use Vercel v0 to generate UI components', 'beginner' ),
        array( 'best AI tools for data science and machine learning', 'intermediate' ),
        array( 'how to prompt AI for better code output', 'beginner' ),
        array( 'AI tools for API testing and documentation', 'intermediate' ),
        array( 'how to use AI to convert code between languages', 'intermediate' ),
        array( 'best AI tools for game development', 'intermediate' ),
        array( 'how to build a chatbot with Python and AI', 'intermediate' ),
        array( 'AI security scanning tools for developers', 'advanced' ),
        array( 'how to use AI for regex pattern creation', 'beginner' ),
        array( 'best AI terminal and command line tools', 'intermediate' ),
        array( 'how to use Claude Code for development workflow', 'intermediate' ),
        array( 'AI tools for Git commit messages and PR reviews', 'beginner' ),
        array( 'how to automate testing with AI tools', 'intermediate' ),
        array( 'best AI tools for backend development Node.js', 'intermediate' ),
        array( 'how to use Bolt.new AI for full stack apps', 'beginner' ),
        array( 'AI tools for performance optimization', 'advanced' ),
        array( 'how to use Windsurf AI code editor', 'beginner' ),
        array( 'best AI tools for Docker and containerization', 'advanced' ),
        array( 'how to build Chrome extensions with AI', 'intermediate' ),
        array( 'AI tools for responsive design testing', 'beginner' ),
        array( 'how to create Telegram bots with AI help', 'intermediate' ),
    ),

    // ------- AI Data Analysis -------
    'ai-data-analysis' => array(
        array( 'how to use ChatGPT for data analysis beginners', 'beginner' ),
        array( 'best AI tools for Excel data analysis', 'beginner' ),
        array( 'how to create charts and graphs with AI', 'beginner' ),
        array( 'ChatGPT advanced data analysis upload files', 'beginner' ),
        array( 'how to use AI to clean messy data', 'beginner' ),
        array( 'best AI tools for business intelligence', 'intermediate' ),
        array( 'how to use Claude for CSV data analysis', 'beginner' ),
        array( 'AI tools for survey data analysis', 'beginner' ),
        array( 'how to create dashboards with AI tools', 'intermediate' ),
        array( 'best AI powered spreadsheet tools', 'beginner' ),
        array( 'how to use AI for financial data analysis', 'intermediate' ),
        array( 'AI tools for sentiment analysis of reviews', 'intermediate' ),
        array( 'how to visualize data with AI automatically', 'beginner' ),
        array( 'best AI tools for market research', 'intermediate' ),
        array( 'how to use Python pandas with ChatGPT', 'intermediate' ),
        array( 'AI tools for competitor analysis', 'intermediate' ),
        array( 'how to use AI for sales data forecasting', 'intermediate' ),
        array( 'best no code AI analytics platforms', 'beginner' ),
        array( 'how to use AI to find patterns in data', 'beginner' ),
        array( 'AI tools for web scraping and data collection', 'intermediate' ),
        array( 'how to create pivot tables with AI help', 'beginner' ),
        array( 'best AI tools for Google Analytics insights', 'intermediate' ),
        array( 'how to use AI for A/B testing analysis', 'intermediate' ),
        array( 'AI tools for social media analytics', 'beginner' ),
        array( 'how to use AI for SEO data analysis', 'intermediate' ),
        array( 'best AI tools for customer data analysis', 'intermediate' ),
        array( 'how to use NotebookLM for research analysis', 'beginner' ),
        array( 'AI tools for real estate market analysis', 'intermediate' ),
        array( 'how to use AI for inventory data management', 'intermediate' ),
        array( 'best AI tools for academic research data', 'intermediate' ),
        array( 'how to use ChatGPT with Google Sheets formulas', 'beginner' ),
        array( 'AI tools for HR and workforce analytics', 'intermediate' ),
        array( 'how to automate reports with AI tools', 'intermediate' ),
        array( 'best AI tools for ecommerce analytics', 'intermediate' ),
        array( 'how to use AI for healthcare data analysis', 'advanced' ),
        array( 'AI powered PDF data extraction tools', 'beginner' ),
        array( 'how to use Julius AI for data analysis', 'beginner' ),
        array( 'best AI tools for statistical analysis', 'intermediate' ),
        array( 'how to create infographics with AI from data', 'beginner' ),
        array( 'AI tools for supply chain analytics', 'advanced' ),
    ),

    // ------- AI Writing -------
    'ai-writing' => array(
        array( 'how to use ChatGPT to write blog posts', 'beginner' ),
        array( 'best AI writing tools compared', 'beginner' ),
        array( 'how to use AI to write SEO optimized content', 'intermediate' ),
        array( 'ChatGPT prompts for creative writing stories', 'beginner' ),
        array( 'how to use Claude for long form writing', 'beginner' ),
        array( 'best AI tools for copywriting ads and sales', 'beginner' ),
        array( 'how to use AI to write product descriptions', 'beginner' ),
        array( 'AI tools for grammar checking and editing', 'beginner' ),
        array( 'how to make AI writing sound more human', 'intermediate' ),
        array( 'best AI tools for email writing and outreach', 'beginner' ),
        array( 'how to use AI to write newsletters', 'beginner' ),
        array( 'AI tools for academic writing and essays', 'beginner' ),
        array( 'how to use ChatGPT to write a book', 'intermediate' ),
        array( 'best AI tools for social media captions', 'beginner' ),
        array( 'how to use AI to rewrite and paraphrase text', 'beginner' ),
        array( 'AI tools for resume and cover letter writing', 'beginner' ),
        array( 'how to use Jasper AI for marketing content', 'intermediate' ),
        array( 'best AI tools for technical writing', 'intermediate' ),
        array( 'how to create a content calendar with AI', 'beginner' ),
        array( 'AI tools for scriptwriting YouTube videos', 'beginner' ),
        array( 'how to use AI to write Amazon product listings', 'intermediate' ),
        array( 'best AI tools for translation and localization', 'beginner' ),
        array( 'how to detect AI generated text tools comparison', 'beginner' ),
        array( 'AI tools for press release writing', 'intermediate' ),
        array( 'how to use AI to outline articles and essays', 'beginner' ),
        array( 'best AI tools for poetry and creative writing', 'beginner' ),
        array( 'how to use ChatGPT to write case studies', 'intermediate' ),
        array( 'AI tools for website copy and landing pages', 'intermediate' ),
        array( 'how to batch create content with AI tools', 'intermediate' ),
        array( 'best AI writing assistants for non native speakers', 'beginner' ),
        array( 'how to use AI to write white papers', 'advanced' ),
        array( 'AI tools for legal document writing', 'intermediate' ),
        array( 'how to create FAQ pages with AI', 'beginner' ),
        array( 'best AI tools for brand voice consistency', 'intermediate' ),
        array( 'how to use AI to write Shopify product pages', 'beginner' ),
        array( 'AI tools for headline and title generation', 'beginner' ),
        array( 'how to proofread content with AI tools', 'beginner' ),
        array( 'best AI writing tools for WordPress blogs', 'beginner' ),
        array( 'how to use AI to create email sequences', 'intermediate' ),
        array( 'AI tools for writing grant proposals', 'advanced' ),
    ),

    // ------- AI Video & Audio -------
    'ai-video-audio' => array(
        array( 'how to use Suno AI to create music', 'beginner' ),
        array( 'best AI video generators from text', 'beginner' ),
        array( 'how to use Runway ML for video editing', 'beginner' ),
        array( 'AI tools for removing vocals from songs', 'beginner' ),
        array( 'how to create AI voiceover for videos', 'beginner' ),
        array( 'best AI tools for video editing beginners', 'beginner' ),
        array( 'how to use ElevenLabs for AI voice cloning', 'intermediate' ),
        array( 'AI tools for podcast transcription', 'beginner' ),
        array( 'how to create AI generated music for YouTube', 'beginner' ),
        array( 'best text to speech AI tools compared', 'beginner' ),
        array( 'how to use Kling AI for video generation', 'beginner' ),
        array( 'AI tools for automatic video subtitles', 'beginner' ),
        array( 'how to use Sora AI for video creation', 'intermediate' ),
        array( 'best AI tools for audio noise removal', 'beginner' ),
        array( 'how to create AI music for commercial use', 'intermediate' ),
        array( 'AI tools for video background removal', 'beginner' ),
        array( 'how to use Descript for AI video editing', 'beginner' ),
        array( 'best AI tools for YouTube content creators', 'beginner' ),
        array( 'how to clone your voice with AI safely', 'intermediate' ),
        array( 'AI tools for music production and mixing', 'intermediate' ),
        array( 'how to create AI animated videos', 'intermediate' ),
        array( 'best AI tools for screen recording and editing', 'beginner' ),
        array( 'how to use HeyGen for AI avatar videos', 'beginner' ),
        array( 'AI tools for audio mastering and enhancement', 'intermediate' ),
        array( 'how to create AI video ads for social media', 'intermediate' ),
        array( 'best AI tools for video upscaling', 'beginner' ),
        array( 'how to create faceless YouTube videos with AI', 'beginner' ),
        array( 'AI tools for real time voice translation', 'intermediate' ),
        array( 'how to use Pika AI for video generation', 'beginner' ),
        array( 'best AI tools for sound effects generation', 'beginner' ),
        array( 'how to create audiobooks with AI voice', 'intermediate' ),
        array( 'AI tools for video summarization', 'beginner' ),
        array( 'how to use Udio AI for music generation', 'beginner' ),
        array( 'best AI tools for live streaming enhancement', 'intermediate' ),
        array( 'how to create AI video presentations', 'beginner' ),
        array( 'AI dubbing tools for multilingual videos', 'intermediate' ),
        array( 'how to use Luma AI for 3D video', 'intermediate' ),
        array( 'best AI tools for video thumbnails', 'beginner' ),
        array( 'how to create podcast clips with AI automatically', 'beginner' ),
        array( 'AI tools for speech to text accurate transcription', 'beginner' ),
    ),

    // ------- AI for Business -------
    'ai-business' => array(
        array( 'how to use AI to automate business tasks', 'beginner' ),
        array( 'best AI tools for small business owners', 'beginner' ),
        array( 'how to use ChatGPT for customer service', 'beginner' ),
        array( 'AI tools for email marketing automation', 'beginner' ),
        array( 'how to create AI chatbot for your website', 'intermediate' ),
        array( 'best AI tools for project management', 'beginner' ),
        array( 'how to use AI for social media management', 'beginner' ),
        array( 'AI tools for accounting and bookkeeping', 'beginner' ),
        array( 'how to use AI for lead generation', 'intermediate' ),
        array( 'best AI tools for sales and CRM', 'intermediate' ),
        array( 'how to automate workflows with Zapier and AI', 'intermediate' ),
        array( 'AI tools for meeting notes and transcription', 'beginner' ),
        array( 'how to use AI for competitive analysis', 'intermediate' ),
        array( 'best AI tools for HR and recruitment', 'intermediate' ),
        array( 'how to create business plans with AI', 'beginner' ),
        array( 'AI tools for inventory management', 'intermediate' ),
        array( 'how to use AI for pricing strategy', 'intermediate' ),
        array( 'best AI tools for ecommerce store owners', 'beginner' ),
        array( 'how to use AI chatbots for appointment booking', 'beginner' ),
        array( 'AI tools for brand monitoring and reputation', 'intermediate' ),
        array( 'how to use AI for content marketing strategy', 'intermediate' ),
        array( 'best AI tools for startup founders', 'beginner' ),
        array( 'how to create SOPs with AI tools', 'beginner' ),
        array( 'AI tools for document management and search', 'beginner' ),
        array( 'how to use AI for market trend prediction', 'advanced' ),
        array( 'best AI tools for real estate agents', 'beginner' ),
        array( 'how to automate reporting with AI dashboards', 'intermediate' ),
        array( 'AI tools for restaurant and food business', 'beginner' ),
        array( 'how to use AI for supply chain optimization', 'advanced' ),
        array( 'best AI personal assistant tools for productivity', 'beginner' ),
        array( 'how to use AI for contract review and analysis', 'intermediate' ),
        array( 'AI tools for influencer marketing', 'intermediate' ),
        array( 'how to create training materials with AI', 'beginner' ),
        array( 'best AI tools for legal professionals', 'intermediate' ),
        array( 'how to use Make.com with AI for automation', 'intermediate' ),
        array( 'AI tools for customer feedback analysis', 'intermediate' ),
        array( 'how to create pitch decks with AI', 'beginner' ),
        array( 'best AI tools for dropshipping business', 'beginner' ),
        array( 'how to use AI for financial planning', 'intermediate' ),
        array( 'AI tools for nonprofit organizations', 'beginner' ),
    ),
);

// Seed keywords.
$total = 0;
foreach ( $keywords as $category => $kw_list ) {
    $count = 0;
    foreach ( $kw_list as $kw ) {
        $added = QWE_DB::add_keyword( $kw[0], $category, $kw[1] );
        if ( $added ) {
            $count++;
        }
    }
    $total += $count;
    echo "  {$category}: {$count} keywords added\n";
}

echo "\nTotal: {$total} new keywords seeded.\n";

// Show stats.
$pending = QWE_DB::count_pending_keywords();
echo "\nPending keywords per category:\n";
foreach ( $pending as $cat => $cnt ) {
    echo "  {$cat}: {$cnt}\n";
}

echo "\nSetup complete.\n";
